version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - tomcat    
    depends_on:
      - tomcat
    networks:
      - spring
      
  tomcat:
    container_name: tomcat9
    build: ./
    #restart: on-failure
    ports:
      - 8080:8080
    networks:
      - spring

networks:
  spring:
    external: false