version: '3.8'
services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./app:/app/node_modules
    ports:
      - '3000:3000'
