version: '3.9'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./www:/var/www/html/
        ports:
            - 8000:80

    redis2:
        image: redis:latest
        ports:
            - 6379:6379
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ./redis/data:/data

    redis-admin:
        image: erikdubbelboer/phpredisadmin:latest
        environment:
        - ADMIN_USER=admin
        - ADMIN_PASS=admin
        - REDIS_1_HOST=redis2
        - REDIS_1_PORT=6379
        ports:
            - 23567:80
        depends_on:
            - redis2
